"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['xtoolite.py']
DATA_FILES = []
OPTIONS = {'iconfile': './icons/iconMain.icns', 'includes': "*"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
